// Mocks generated by Mockito 5.4.4 from annotations
// in my_recipe_book/test/mixing_analysis_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_recipe_book/core/types/environment_types.dart' as _i6;
import 'package:my_recipe_book/models/advanced_sous_chef_models.dart' as _i5;
import 'package:my_recipe_book/services/mixing_analysis_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeColor_0 extends _i1.SmartFake implements _i2.Color {
  _FakeColor_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MixingAnalysisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMixingAnalysisService extends _i1.Mock
    implements _i3.MixingAnalysisService {
  MockMixingAnalysisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> extractMixingSteps(
          Map<String, dynamic>? recipeData) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractMixingSteps,
          [recipeData],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  Map<String, dynamic> analyzeMixingStep(
    Map<String, dynamic>? step,
    int? stepIndex,
    Map<String, dynamic>? previousStepAnalysis,
    Map<String, dynamic>? previousDoughState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeMixingStep,
          [
            step,
            stepIndex,
            previousStepAnalysis,
            previousDoughState,
          ],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<Map<String, dynamic>> performComprehensiveAnalysis(
    List<Map<String, dynamic>>? stepAnalyses,
    Map<String, dynamic>? recipeData, {
    List<Map<String, dynamic>>? ingredients,
    List<Map<String, dynamic>>? mixingSteps,
    _i5.MixingMeta? mixingMeta,
    _i6.MixerType? mixerType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performComprehensiveAnalysis,
          [
            stepAnalyses,
            recipeData,
          ],
          {
            #ingredients: ingredients,
            #mixingSteps: mixingSteps,
            #mixingMeta: mixingMeta,
            #mixerType: mixerType,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i2.Color getGlutenColor(double? glutenFormation) => (super.noSuchMethod(
        Invocation.method(
          #getGlutenColor,
          [glutenFormation],
        ),
        returnValue: _FakeColor_0(
          this,
          Invocation.method(
            #getGlutenColor,
            [glutenFormation],
          ),
        ),
      ) as _i2.Color);

  @override
  _i2.Color getMoistureAbsorptionColor(double? moistureAbsorption) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoistureAbsorptionColor,
          [moistureAbsorption],
        ),
        returnValue: _FakeColor_0(
          this,
          Invocation.method(
            #getMoistureAbsorptionColor,
            [moistureAbsorption],
          ),
        ),
      ) as _i2.Color);

  @override
  _i2.Color getViscosityColor(double? viscosity) => (super.noSuchMethod(
        Invocation.method(
          #getViscosityColor,
          [viscosity],
        ),
        returnValue: _FakeColor_0(
          this,
          Invocation.method(
            #getViscosityColor,
            [viscosity],
          ),
        ),
      ) as _i2.Color);

  @override
  _i2.Color getTemperatureColor(double? temperature) => (super.noSuchMethod(
        Invocation.method(
          #getTemperatureColor,
          [temperature],
        ),
        returnValue: _FakeColor_0(
          this,
          Invocation.method(
            #getTemperatureColor,
            [temperature],
          ),
        ),
      ) as _i2.Color);

  @override
  _i2.Color getScoreColor(double? score) => (super.noSuchMethod(
        Invocation.method(
          #getScoreColor,
          [score],
        ),
        returnValue: _FakeColor_0(
          this,
          Invocation.method(
            #getScoreColor,
            [score],
          ),
        ),
      ) as _i2.Color);

  @override
  Map<String, dynamic> createStepAnalysisWithAccumulation(
    Map<String, dynamic>? step,
    int? index,
    Map<String, dynamic>? previousDoughState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStepAnalysisWithAccumulation,
          [
            step,
            index,
            previousDoughState,
          ],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> createDefaultStepAnalysis(
    Map<String, dynamic>? step,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDefaultStepAnalysis,
          [
            step,
            index,
          ],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> generateSimpleAnalysisResult(
          List<Map<String, dynamic>>? mixingSteps) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSimpleAnalysisResult,
          [mixingSteps],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  List<String> generateCurrentStatusWithWarnings(
          List<Map<String, dynamic>>? mixingSteps) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateCurrentStatusWithWarnings,
          [mixingSteps],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i2.Color getMetricColor(
    String? metricType,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMetricColor,
          [
            metricType,
            value,
          ],
        ),
        returnValue: _FakeColor_0(
          this,
          Invocation.method(
            #getMetricColor,
            [
              metricType,
              value,
            ],
          ),
        ),
      ) as _i2.Color);

  @override
  double calculateGlutenFormationIncrement({
    required int? stepIndex,
    required String? speed,
    required int? duration,
    required double? currentGluten,
    required double? temperature,
    int? totalSteps = 4,
    List<Map<String, dynamic>>? ingredients,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateGlutenFormationIncrement,
          [],
          {
            #stepIndex: stepIndex,
            #speed: speed,
            #duration: duration,
            #currentGluten: currentGluten,
            #temperature: temperature,
            #totalSteps: totalSteps,
            #ingredients: ingredients,
          },
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double calculateViscosity(
    int? stepIndex,
    String? speed,
    int? duration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateViscosity,
          [
            stepIndex,
            speed,
            duration,
          ],
        ),
        returnValue: 0.0,
      ) as double);
}
