// Mocks generated by Mockito 5.4.4 from annotations
// in my_recipe_book/test/widgets/modular_calculator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_recipe_book/models/user_configuration.dart' as _i2;
import 'package:my_recipe_book/services/user_settings_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserConfiguration_0 extends _i1.SmartFake
    implements _i2.UserConfiguration {
  _FakeUserConfiguration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsService extends _i1.Mock
    implements _i3.UserSettingsService {
  MockUserSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserConfiguration> loadUserConfiguration(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadUserConfiguration,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.UserConfiguration>.value(_FakeUserConfiguration_0(
          this,
          Invocation.method(
            #loadUserConfiguration,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.UserConfiguration>);

  @override
  _i4.Future<void> saveUserConfiguration(_i2.UserConfiguration? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserConfiguration,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveModuleLayout(Map<String, _i5.Offset>? layout) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveModuleLayout,
          [layout],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, _i5.Offset>> loadModuleLayout() => (super.noSuchMethod(
        Invocation.method(
          #loadModuleLayout,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, _i5.Offset>>.value(<String, _i5.Offset>{}),
      ) as _i4.Future<Map<String, _i5.Offset>>);

  @override
  _i4.Future<void> updateActiveModules(List<String>? modules) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateActiveModules,
          [modules],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> loadActiveModules() => (super.noSuchMethod(
        Invocation.method(
          #loadActiveModules,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> resetSettings(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #resetSettings,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTextScaleFactor(
    String? userId,
    double? scaleFactor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTextScaleFactor,
          [
            userId,
            scaleFactor,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUseSystemTextScale(
    String? userId,
    bool? useSystem,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUseSystemTextScale,
          [
            userId,
            useSystem,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSettings,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
