// Mocks generated by Mockito 5.4.4 from annotations
// in my_recipe_book/test/services/analysis_modules_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:my_recipe_book/models/advanced_sous_chef_models.dart' as _i2;
import 'package:my_recipe_book/models/analysis_options.dart' as _i3;
import 'package:my_recipe_book/models/analysis_request.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecipe_0 extends _i1.SmartFake implements _i2.Recipe {
  _FakeRecipe_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalysisOptions_1 extends _i1.SmartFake
    implements _i3.AnalysisOptions {
  _FakeAnalysisOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalysisRequest_3 extends _i1.SmartFake
    implements _i4.AnalysisRequest {
  _FakeAnalysisRequest_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIngredient_4 extends _i1.SmartFake implements _i2.Ingredient {
  _FakeIngredient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOvenCharacteristics_5 extends _i1.SmartFake
    implements _i2.OvenCharacteristics {
  _FakeOvenCharacteristics_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnvironmentalConditions_6 extends _i1.SmartFake
    implements _i2.EnvironmentalConditions {
  _FakeEnvironmentalConditions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AnalysisRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalysisRequest extends _i1.Mock implements _i4.AnalysisRequest {
  MockAnalysisRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i2.Recipe get recipe => (super.noSuchMethod(
        Invocation.getter(#recipe),
        returnValue: _FakeRecipe_0(
          this,
          Invocation.getter(#recipe),
        ),
      ) as _i2.Recipe);

  @override
  List<dynamic> get ingredients => (super.noSuchMethod(
        Invocation.getter(#ingredients),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  _i3.AnalysisOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeAnalysisOptions_1(
          this,
          Invocation.getter(#options),
        ),
      ) as _i3.AnalysisOptions);

  @override
  DateTime get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: _FakeDateTime_2(
          this,
          Invocation.getter(#createdAt),
        ),
      ) as DateTime);

  @override
  int get priority => (super.noSuchMethod(
        Invocation.getter(#priority),
        returnValue: 0,
      ) as int);

  @override
  Map<String, dynamic> get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  int get retryCount => (super.noSuchMethod(
        Invocation.getter(#retryCount),
        returnValue: 0,
      ) as int);

  @override
  String get priorityString => (super.noSuchMethod(
        Invocation.getter(#priorityString),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#priorityString),
        ),
      ) as String);

  @override
  int get ageInSeconds => (super.noSuchMethod(
        Invocation.getter(#ageInSeconds),
        returnValue: 0,
      ) as int);

  @override
  _i4.AnalysisRequest copyWith({
    String? id,
    _i2.Recipe? recipe,
    List<dynamic>? ingredients,
    dynamic environment,
    _i3.AnalysisOptions? options,
    DateTime? createdAt,
    int? priority,
    String? userId,
    Map<String, dynamic>? metadata,
    int? retryCount,
    Map<String, dynamic>? results,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #id: id,
            #recipe: recipe,
            #ingredients: ingredients,
            #environment: environment,
            #options: options,
            #createdAt: createdAt,
            #priority: priority,
            #userId: userId,
            #metadata: metadata,
            #retryCount: retryCount,
            #results: results,
          },
        ),
        returnValue: _FakeAnalysisRequest_3(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #recipe: recipe,
              #ingredients: ingredients,
              #environment: environment,
              #options: options,
              #createdAt: createdAt,
              #priority: priority,
              #userId: userId,
              #metadata: metadata,
              #retryCount: retryCount,
              #results: results,
            },
          ),
        ),
      ) as _i4.AnalysisRequest);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool isValid() => (super.noSuchMethod(
        Invocation.method(
          #isValid,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  int estimateSize() => (super.noSuchMethod(
        Invocation.method(
          #estimateSize,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  String generateCacheKey() => (super.noSuchMethod(
        Invocation.method(
          #generateCacheKey,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateCacheKey,
            [],
          ),
        ),
      ) as String);

  @override
  String getSummary() => (super.noSuchMethod(
        Invocation.method(
          #getSummary,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSummary,
            [],
          ),
        ),
      ) as String);

  @override
  int estimateProcessingTime() => (super.noSuchMethod(
        Invocation.method(
          #estimateProcessingTime,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int estimateMemoryUsage() => (super.noSuchMethod(
        Invocation.method(
          #estimateMemoryUsage,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool isExpired({int? maxAgeMinutes = 30}) => (super.noSuchMethod(
        Invocation.method(
          #isExpired,
          [],
          {#maxAgeMinutes: maxAgeMinutes},
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [Recipe].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipe extends _i1.Mock implements _i2.Recipe {
  MockRecipe() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  List<_i2.Ingredient> get ingredients => (super.noSuchMethod(
        Invocation.getter(#ingredients),
        returnValue: <_i2.Ingredient>[],
      ) as List<_i2.Ingredient>);

  @override
  List<String> get processes => (super.noSuchMethod(
        Invocation.getter(#processes),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i2.RecipeCategory get category => (super.noSuchMethod(
        Invocation.getter(#category),
        returnValue: _i2.RecipeCategory.bread,
      ) as _i2.RecipeCategory);

  @override
  DateTime get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: _FakeDateTime_2(
          this,
          Invocation.getter(#createdAt),
        ),
      ) as DateTime);

  @override
  DateTime get updatedAt => (super.noSuchMethod(
        Invocation.getter(#updatedAt),
        returnValue: _FakeDateTime_2(
          this,
          Invocation.getter(#updatedAt),
        ),
      ) as DateTime);

  @override
  double get flourAmount => (super.noSuchMethod(
        Invocation.getter(#flourAmount),
        returnValue: 0.0,
      ) as double);

  @override
  double get hydrationPercentage => (super.noSuchMethod(
        Invocation.getter(#hydrationPercentage),
        returnValue: 0.0,
      ) as double);

  @override
  double get saltPercentage => (super.noSuchMethod(
        Invocation.getter(#saltPercentage),
        returnValue: 0.0,
      ) as double);

  @override
  double get yeastPercentage => (super.noSuchMethod(
        Invocation.getter(#yeastPercentage),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.Recipe copyWith({
    String? title,
    List<_i2.Ingredient>? ingredients,
    List<String>? processes,
    _i2.RecipeCategory? category,
    String? description,
    DateTime? createdAt,
    DateTime? updatedAt,
    List<Map<String, dynamic>>? mixingSteps,
    List<Map<String, dynamic>>? fermentationSteps,
    List<Map<String, dynamic>>? ovenSteps,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #title: title,
            #ingredients: ingredients,
            #processes: processes,
            #category: category,
            #description: description,
            #createdAt: createdAt,
            #updatedAt: updatedAt,
            #mixingSteps: mixingSteps,
            #fermentationSteps: fermentationSteps,
            #ovenSteps: ovenSteps,
          },
        ),
        returnValue: _FakeRecipe_0(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #title: title,
              #ingredients: ingredients,
              #processes: processes,
              #category: category,
              #description: description,
              #createdAt: createdAt,
              #updatedAt: updatedAt,
              #mixingSteps: mixingSteps,
              #fermentationSteps: fermentationSteps,
              #ovenSteps: ovenSteps,
            },
          ),
        ),
      ) as _i2.Recipe);
}

/// A class which mocks [Ingredient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredient extends _i1.Mock implements _i2.Ingredient {
  MockIngredient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  double get amount => (super.noSuchMethod(
        Invocation.getter(#amount),
        returnValue: 0.0,
      ) as double);

  @override
  String get unit => (super.noSuchMethod(
        Invocation.getter(#unit),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#unit),
        ),
      ) as String);

  @override
  Map<String, dynamic> get properties => (super.noSuchMethod(
        Invocation.getter(#properties),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get isFlour => (super.noSuchMethod(
        Invocation.getter(#isFlour),
        returnValue: false,
      ) as bool);

  @override
  bool get isWater => (super.noSuchMethod(
        Invocation.getter(#isWater),
        returnValue: false,
      ) as bool);

  @override
  bool get isSalt => (super.noSuchMethod(
        Invocation.getter(#isSalt),
        returnValue: false,
      ) as bool);

  @override
  bool get isYeast => (super.noSuchMethod(
        Invocation.getter(#isYeast),
        returnValue: false,
      ) as bool);

  @override
  bool get isSugar => (super.noSuchMethod(
        Invocation.getter(#isSugar),
        returnValue: false,
      ) as bool);

  @override
  bool get isFat => (super.noSuchMethod(
        Invocation.getter(#isFat),
        returnValue: false,
      ) as bool);

  @override
  double get proteinContent => (super.noSuchMethod(
        Invocation.getter(#proteinContent),
        returnValue: 0.0,
      ) as double);

  @override
  double get moistureContent => (super.noSuchMethod(
        Invocation.getter(#moistureContent),
        returnValue: 0.0,
      ) as double);

  @override
  double get fatContent => (super.noSuchMethod(
        Invocation.getter(#fatContent),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.Ingredient copyWith({
    String? name,
    double? amount,
    String? unit,
    Map<String, dynamic>? properties,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #name: name,
            #amount: amount,
            #unit: unit,
            #properties: properties,
          },
        ),
        returnValue: _FakeIngredient_4(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #name: name,
              #amount: amount,
              #unit: unit,
              #properties: properties,
            },
          ),
        ),
      ) as _i2.Ingredient);
}

/// A class which mocks [EnvironmentalConditions].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnvironmentalConditions extends _i1.Mock
    implements _i2.EnvironmentalConditions {
  MockEnvironmentalConditions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get temperature => (super.noSuchMethod(
        Invocation.getter(#temperature),
        returnValue: 0.0,
      ) as double);

  @override
  double get humidity => (super.noSuchMethod(
        Invocation.getter(#humidity),
        returnValue: 0.0,
      ) as double);

  @override
  double get pressure => (super.noSuchMethod(
        Invocation.getter(#pressure),
        returnValue: 0.0,
      ) as double);

  @override
  _i2.Season get season => (super.noSuchMethod(
        Invocation.getter(#season),
        returnValue: _i2.Season.spring,
      ) as _i2.Season);

  @override
  _i2.OvenCharacteristics get oven => (super.noSuchMethod(
        Invocation.getter(#oven),
        returnValue: _FakeOvenCharacteristics_5(
          this,
          Invocation.getter(#oven),
        ),
      ) as _i2.OvenCharacteristics);

  @override
  double get temperatureCorrection => (super.noSuchMethod(
        Invocation.getter(#temperatureCorrection),
        returnValue: 0.0,
      ) as double);

  @override
  double get humidityCorrection => (super.noSuchMethod(
        Invocation.getter(#humidityCorrection),
        returnValue: 0.0,
      ) as double);

  @override
  double get altitudeCorrection => (super.noSuchMethod(
        Invocation.getter(#altitudeCorrection),
        returnValue: 0.0,
      ) as double);

  @override
  double get fermentationSpeedCorrection => (super.noSuchMethod(
        Invocation.getter(#fermentationSpeedCorrection),
        returnValue: 0.0,
      ) as double);

  @override
  List<String> get heatManagementRecommendations => (super.noSuchMethod(
        Invocation.getter(#heatManagementRecommendations),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get safeHeatManagementTips => (super.noSuchMethod(
        Invocation.getter(#safeHeatManagementTips),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get riskyHeatManagementTips => (super.noSuchMethod(
        Invocation.getter(#riskyHeatManagementTips),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get coldManagementRecommendations => (super.noSuchMethod(
        Invocation.getter(#coldManagementRecommendations),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get safeColdManagementTips => (super.noSuchMethod(
        Invocation.getter(#safeColdManagementTips),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get riskyColdManagementTips => (super.noSuchMethod(
        Invocation.getter(#riskyColdManagementTips),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.EnvironmentalConditions copyWith({
    double? temperature,
    double? humidity,
    double? pressure,
    _i2.Season? season,
    _i2.OvenCharacteristics? oven,
    double? altitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #temperature: temperature,
            #humidity: humidity,
            #pressure: pressure,
            #season: season,
            #oven: oven,
            #altitude: altitude,
          },
        ),
        returnValue: _FakeEnvironmentalConditions_6(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #temperature: temperature,
              #humidity: humidity,
              #pressure: pressure,
              #season: season,
              #oven: oven,
              #altitude: altitude,
            },
          ),
        ),
      ) as _i2.EnvironmentalConditions);
}

/// A class which mocks [AnalysisOptions].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalysisOptions extends _i1.Mock implements _i3.AnalysisOptions {
  MockAnalysisOptions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get enabledModules => (super.noSuchMethod(
        Invocation.getter(#enabledModules),
        returnValue: <String>[],
      ) as List<String>);

  @override
  int get analysisDepth => (super.noSuchMethod(
        Invocation.getter(#analysisDepth),
        returnValue: 0,
      ) as int);

  @override
  bool get useCache => (super.noSuchMethod(
        Invocation.getter(#useCache),
        returnValue: false,
      ) as bool);

  @override
  bool get enableParallelProcessing => (super.noSuchMethod(
        Invocation.getter(#enableParallelProcessing),
        returnValue: false,
      ) as bool);

  @override
  int get maxProcessingTime => (super.noSuchMethod(
        Invocation.getter(#maxProcessingTime),
        returnValue: 0,
      ) as int);

  @override
  int get precisionLevel => (super.noSuchMethod(
        Invocation.getter(#precisionLevel),
        returnValue: 0,
      ) as int);

  @override
  bool get generateRecommendations => (super.noSuchMethod(
        Invocation.getter(#generateRecommendations),
        returnValue: false,
      ) as bool);

  @override
  bool get includeNutritionalAnalysis => (super.noSuchMethod(
        Invocation.getter(#includeNutritionalAnalysis),
        returnValue: false,
      ) as bool);

  @override
  bool get includeCostAnalysis => (super.noSuchMethod(
        Invocation.getter(#includeCostAnalysis),
        returnValue: false,
      ) as bool);

  @override
  bool get includeEnvironmentalImpact => (super.noSuchMethod(
        Invocation.getter(#includeEnvironmentalImpact),
        returnValue: false,
      ) as bool);

  @override
  bool get includeAllergyAnalysis => (super.noSuchMethod(
        Invocation.getter(#includeAllergyAnalysis),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> get customParameters => (super.noSuchMethod(
        Invocation.getter(#customParameters),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String get outputFormat => (super.noSuchMethod(
        Invocation.getter(#outputFormat),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#outputFormat),
        ),
      ) as String);

  @override
  String get language => (super.noSuchMethod(
        Invocation.getter(#language),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#language),
        ),
      ) as String);

  @override
  bool get debugMode => (super.noSuchMethod(
        Invocation.getter(#debugMode),
        returnValue: false,
      ) as bool);

  @override
  bool get allowTimeout => (super.noSuchMethod(
        Invocation.getter(#allowTimeout),
        returnValue: false,
      ) as bool);

  @override
  bool get allowPartialResults => (super.noSuchMethod(
        Invocation.getter(#allowPartialResults),
        returnValue: false,
      ) as bool);

  @override
  _i3.AnalysisOptions copyWith({
    List<String>? enabledModules,
    int? analysisDepth,
    bool? useCache,
    bool? enableParallelProcessing,
    int? maxProcessingTime,
    int? precisionLevel,
    bool? generateRecommendations,
    bool? includeNutritionalAnalysis,
    bool? includeCostAnalysis,
    bool? includeEnvironmentalImpact,
    bool? includeAllergyAnalysis,
    Map<String, dynamic>? customParameters,
    String? outputFormat,
    String? language,
    bool? debugMode,
    bool? allowTimeout,
    bool? allowPartialResults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #enabledModules: enabledModules,
            #analysisDepth: analysisDepth,
            #useCache: useCache,
            #enableParallelProcessing: enableParallelProcessing,
            #maxProcessingTime: maxProcessingTime,
            #precisionLevel: precisionLevel,
            #generateRecommendations: generateRecommendations,
            #includeNutritionalAnalysis: includeNutritionalAnalysis,
            #includeCostAnalysis: includeCostAnalysis,
            #includeEnvironmentalImpact: includeEnvironmentalImpact,
            #includeAllergyAnalysis: includeAllergyAnalysis,
            #customParameters: customParameters,
            #outputFormat: outputFormat,
            #language: language,
            #debugMode: debugMode,
            #allowTimeout: allowTimeout,
            #allowPartialResults: allowPartialResults,
          },
        ),
        returnValue: _FakeAnalysisOptions_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #enabledModules: enabledModules,
              #analysisDepth: analysisDepth,
              #useCache: useCache,
              #enableParallelProcessing: enableParallelProcessing,
              #maxProcessingTime: maxProcessingTime,
              #precisionLevel: precisionLevel,
              #generateRecommendations: generateRecommendations,
              #includeNutritionalAnalysis: includeNutritionalAnalysis,
              #includeCostAnalysis: includeCostAnalysis,
              #includeEnvironmentalImpact: includeEnvironmentalImpact,
              #includeAllergyAnalysis: includeAllergyAnalysis,
              #customParameters: customParameters,
              #outputFormat: outputFormat,
              #language: language,
              #debugMode: debugMode,
              #allowTimeout: allowTimeout,
              #allowPartialResults: allowPartialResults,
            },
          ),
        ),
      ) as _i3.AnalysisOptions);

  @override
  _i3.AnalysisOptions enableModule(String? moduleName) => (super.noSuchMethod(
        Invocation.method(
          #enableModule,
          [moduleName],
        ),
        returnValue: _FakeAnalysisOptions_1(
          this,
          Invocation.method(
            #enableModule,
            [moduleName],
          ),
        ),
      ) as _i3.AnalysisOptions);

  @override
  _i3.AnalysisOptions disableModule(String? moduleName) => (super.noSuchMethod(
        Invocation.method(
          #disableModule,
          [moduleName],
        ),
        returnValue: _FakeAnalysisOptions_1(
          this,
          Invocation.method(
            #disableModule,
            [moduleName],
          ),
        ),
      ) as _i3.AnalysisOptions);

  @override
  _i3.AnalysisOptions enableModules(List<String>? moduleNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableModules,
          [moduleNames],
        ),
        returnValue: _FakeAnalysisOptions_1(
          this,
          Invocation.method(
            #enableModules,
            [moduleNames],
          ),
        ),
      ) as _i3.AnalysisOptions);

  @override
  _i3.AnalysisOptions disableModules(List<String>? moduleNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #disableModules,
          [moduleNames],
        ),
        returnValue: _FakeAnalysisOptions_1(
          this,
          Invocation.method(
            #disableModules,
            [moduleNames],
          ),
        ),
      ) as _i3.AnalysisOptions);

  @override
  bool isModuleEnabled(String? moduleName) => (super.noSuchMethod(
        Invocation.method(
          #isModuleEnabled,
          [moduleName],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.AnalysisOptions addCustomParameter(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCustomParameter,
          [
            key,
            value,
          ],
        ),
        returnValue: _FakeAnalysisOptions_1(
          this,
          Invocation.method(
            #addCustomParameter,
            [
              key,
              value,
            ],
          ),
        ),
      ) as _i3.AnalysisOptions);

  @override
  _i3.AnalysisOptions removeCustomParameter(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeCustomParameter,
          [key],
        ),
        returnValue: _FakeAnalysisOptions_1(
          this,
          Invocation.method(
            #removeCustomParameter,
            [key],
          ),
        ),
      ) as _i3.AnalysisOptions);

  @override
  T? getCustomParameter<T>(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getCustomParameter,
        [key],
      )) as T?);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool isValid() => (super.noSuchMethod(
        Invocation.method(
          #isValid,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  int estimateProcessingTime() => (super.noSuchMethod(
        Invocation.method(
          #estimateProcessingTime,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int estimateMemoryUsage() => (super.noSuchMethod(
        Invocation.method(
          #estimateMemoryUsage,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  double calculateComplexityScore() => (super.noSuchMethod(
        Invocation.method(
          #calculateComplexityScore,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  String getPerformanceGrade() => (super.noSuchMethod(
        Invocation.method(
          #getPerformanceGrade,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getPerformanceGrade,
            [],
          ),
        ),
      ) as String);

  @override
  String getSummary() => (super.noSuchMethod(
        Invocation.method(
          #getSummary,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSummary,
            [],
          ),
        ),
      ) as String);
}
